import type { AuthUser, FluxRecord, Station, SystemConfig } from '@/types'

export const FALLBACK = {
  users: [
    { id: 'u-01', username: 'admin', full_name: '系统超级管理员', institute_name: '虚拟地理环境教育部重点实验室', role: 'ROLE_SUPER_ADMIN' },
    { id: 'u-02', username: 'scientist', full_name: '任教授', institute_name: '地理科学学院生态气象组', role: 'ROLE_FLUX_SCIENTIST' },
    { id: 'u-03', username: 'operator', full_name: '张运维', institute_name: '高寒野外台站观测保障中心', role: 'ROLE_STATION_OPERATOR' },
    { id: 'u-04', username: 'leader', full_name: '南师大院领导', institute_name: '南京师范大学科研院', role: 'ROLE_DECISION_MAKER' },
  ] as AuthUser[],
  stations: [
    {
      id: 'st-01',
      station_code: 'QTP-FLUX-01',
      station_name: '青藏高原那曲高寒草甸通量观测站',
      ecosystem_type: 'ALPINE_MEADOW',
      ecosystem_label: '高寒草甸',
      latitude_masked: '31.4***° N',
      longitude_masked: '91.9***° E',
      altitude_m: 4580,
      tower_height_m: 3.5,
      analyzer_model: 'LI-7500DS / LI-7700 CH4',
      sonic_anemometer_model: 'CSAT3B 3D Sonic',
      battery_voltage: 25.2,
      ambient_temp_c: -8.6,
      rssi_signal_dbm: -75,
      station_status: 'ONLINE',
      status_label: '在线',
      agc_pct: 93,
      heating: false,
    },
    {
      id: 'st-02',
      station_code: 'QTP-FLUX-02',
      station_name: '若尔盖高原泥炭沼泽湿地碳水通量站',
      ecosystem_type: 'ALPINE_WETLAND',
      ecosystem_label: '高寒湿地',
      latitude_masked: '33.6***° N',
      longitude_masked: '102.8***° E',
      altitude_m: 3420,
      tower_height_m: 4,
      analyzer_model: 'EC150 / G2301 Picarro',
      sonic_anemometer_model: 'Gill WindMaster Pro',
      battery_voltage: 24.8,
      ambient_temp_c: -2.4,
      rssi_signal_dbm: -68,
      station_status: 'ONLINE',
      status_label: '在线',
      agc_pct: 91,
      heating: false,
    },
    {
      id: 'st-03',
      station_code: 'QTP-FLUX-03',
      station_name: '风火山多年冻土活动层水热通量站',
      ecosystem_type: 'PERMAFROST_TUNDRA',
      ecosystem_label: '多年冻土苔原',
      latitude_masked: '34.8***° N',
      longitude_masked: '92.9***° E',
      altitude_m: 4720,
      tower_height_m: 3,
      analyzer_model: 'LI-7500DS / LI-7700 CH4',
      sonic_anemometer_model: 'CSAT3B 3D Sonic',
      battery_voltage: 23.4,
      ambient_temp_c: -18.2,
      rssi_signal_dbm: -84,
      station_status: 'WARNING_HEATING',
      status_label: '除霜加热',
      agc_pct: 74.5,
      heating: true,
    },
    {
      id: 'st-04',
      station_code: 'QTP-FLUX-04',
      station_name: '祁连山高寒森林草原过渡带碳水站',
      ecosystem_type: 'FOREST_STEPPE',
      ecosystem_label: '森林草原',
      latitude_masked: '38.4***° N',
      longitude_masked: '99.5***° E',
      altitude_m: 3280,
      tower_height_m: 8,
      analyzer_model: 'LI-7200RS / LI-7700',
      sonic_anemometer_model: 'CSAT3B 3D Sonic',
      battery_voltage: 26.1,
      ambient_temp_c: 4.8,
      rssi_signal_dbm: -62,
      station_status: 'ONLINE',
      status_label: '在线',
      agc_pct: 95,
      heating: false,
    },
  ] as Station[],
  records: [
    { id: 'rec-01', station_id: 'st-01', record_timestamp: '2026-08-14 12:00:00', co2_flux_umol_m2_s: -4.85, ch4_flux_nmol_m2_s: 22.4, h2o_flux_latent_heat_w_m2: 185.6, sensible_heat_w_m2: 120.4, friction_velocity_u_star: 0.42, qc_flag_mauder_foken: 0, wpl_correction_applied: 1, energy_balance_ratio: 0.91, qc_class: 'GOOD' },
    { id: 'rec-02', station_id: 'st-01', record_timestamp: '2026-08-14 12:30:00', co2_flux_umol_m2_s: -5.12, ch4_flux_nmol_m2_s: 24.1, h2o_flux_latent_heat_w_m2: 192, sensible_heat_w_m2: 128.5, friction_velocity_u_star: 0.45, qc_flag_mauder_foken: 0, wpl_correction_applied: 1, energy_balance_ratio: 0.93, qc_class: 'GOOD' },
    { id: 'rec-03', station_id: 'st-01', record_timestamp: '2026-08-14 00:00:00', co2_flux_umol_m2_s: 1.85, ch4_flux_nmol_m2_s: 14.2, h2o_flux_latent_heat_w_m2: 12, sensible_heat_w_m2: -18.4, friction_velocity_u_star: 0.28, qc_flag_mauder_foken: 1, wpl_correction_applied: 1, energy_balance_ratio: 0.84, qc_class: 'GOOD' },
    { id: 'rec-07', station_id: 'st-01', record_timestamp: '2026-08-14 00:30:00', co2_flux_umol_m2_s: 2.14, ch4_flux_nmol_m2_s: 15.8, h2o_flux_latent_heat_w_m2: 8.4, sensible_heat_w_m2: -22.1, friction_velocity_u_star: 0.11, qc_flag_mauder_foken: 6, wpl_correction_applied: 1, energy_balance_ratio: 0.71, qc_class: 'FAIR', night_ustar_fail: true },
    { id: 'rec-08', station_id: 'st-01', record_timestamp: '2026-08-14 01:00:00', co2_flux_umol_m2_s: 1.62, ch4_flux_nmol_m2_s: 13.1, h2o_flux_latent_heat_w_m2: 6.2, sensible_heat_w_m2: -16.8, friction_velocity_u_star: 0.09, qc_flag_mauder_foken: 8, wpl_correction_applied: 0, energy_balance_ratio: 0.62, qc_class: 'BAD', night_ustar_fail: true },
    { id: 'rec-04', station_id: 'st-02', record_timestamp: '2026-08-14 12:00:00', co2_flux_umol_m2_s: -6.3, ch4_flux_nmol_m2_s: 95.8, h2o_flux_latent_heat_w_m2: 220.5, sensible_heat_w_m2: 95.2, friction_velocity_u_star: 0.38, qc_flag_mauder_foken: 0, wpl_correction_applied: 1, energy_balance_ratio: 0.89, qc_class: 'GOOD' },
  ] as FluxRecord[],
  configs: [
    { config_key: 'FEATURE_AUTO_WPL_PIPELINE', config_value: 'true', category: 'FEATURE_FLAG', description: '是否开启 20Hz 原始数据半小时自动 WPL 密度效应与坐标旋转修正' },
    { config_key: 'FEATURE_SM4_GEO_MASKING', config_value: 'true', category: 'SECURITY', description: '是否启用高寒科研野外观测台站精准经纬度国密 SM4 动态脱敏' },
    { config_key: 'USTAR_THRESHOLD_FILTER', config_value: '0.15', category: 'ALGORITHM', description: '夜间摩擦风速 u* 湍流充分发育临界阈值 (m/s)' },
    { config_key: 'AGC_CLEANLINESS_ALERT_THRESHOLD', config_value: '80.0', category: 'MONITOR', description: '分析仪光学信号透过率触发自动除霜加热阈值 (%)' },
  ] as SystemConfig[],
  alerts: [
    { id: 'alt-01', station_id: 'st-03', station_code: 'QTP-FLUX-03', alert_type: 'FROST_CONTAMINATION', optical_agc_signal_pct: 74.5, alert_description: '【低温结霜】分析仪光学镜面透过率降至 74.5%，已自动启动加热带除霜。', auto_deice_triggered: 1, status: 'ACTIVE', alert_time: '2026-08-14 06:18:00' },
    { id: 'alt-02', station_id: 'st-01', station_code: 'QTP-FLUX-01', alert_type: 'LOW_BATTERY', optical_agc_signal_pct: 92, alert_description: '夜间阴雪导致锂电电压轻微波动，已切入超低功耗模式。', auto_deice_triggered: 0, status: 'RESOLVED', alert_time: '2026-08-13 23:40:00' },
  ],
  audit: [{ created_at: '2026-08-14 12:01:00', username: 'admin', action_name: 'LOGIN', station_code: null, status_code: 200 }],
  tender: {
    title: '高寒生态系统CH4 CO2 H2O通量涡度测量系统公开招标公告',
    issuer: '南京师范大学',
    project_no: 'JSZC-320000-SNZX-G2026-0117',
    publish_time: '2026-08-13 16:42',
    keywords: '南京师范大学, 通量涡度测量系统, 涡度相关系统, 温室气体通量监测, 高寒生态系统, JSZC-320000-SNZX-G2026-0117, 江苏政府采购',
    summary: '南京师范大学公开招标高寒生态系统CH4/CO2/H2O通量涡度测量系统，预算金额180万元，接受进口产品投标，合同履行期限为120日历天，投标文件递交截止时间为2026年9月3日09:00。',
    budget: 1800000,
    deadline: '2026-09-03 09:00:00',
    tech_points: [
      '高频多组分温室气体毫秒级流式采集：支持 CH4、CO2、H2O 气体分析仪与三维超声风速计 10Hz~20Hz 连续观测与数据预处理。',
      '微气象通量物理修正全流程流水线：集成二维坐标旋转（2D Rotation）、WPL 密度修正、频谱衰减校正与超声虚温修正。',
      '高寒极端环境低功耗自治与除霜联动：提供野外太阳能电量预测、光学探头结冰智能识别与微环境加温控制。',
      '信创国密脱敏与极简 Serverless 架构：野外台站地理信息国密 SM4 动态脱敏，基于 Cloudflare Workers + D1 实现极简零运维与高弹性。',
    ],
    innovation: [
      '高寒生态系统碳氮水循环数字孪生大屏：实现生态净交换量（NEE）、总初级生产力（GPP）与生态系统呼吸（Re）的半小时尺度高精度实时反演。',
      '通量观测全生命周期质量评估模型：融合能量平衡闭合率检验与非稳态湍流自动剔除，保障气候科研数据国际级公信力。',
    ],
    ca_guide: [
      '登录江苏政府采购“苏采云”系统完成供应商注册、CA 数字证书绑定与实名认证。',
      '下载招标文件，按采购文件编制投标文件，使用符合要求的电子签章完成加密。',
      '于 2026 年 9 月 3 日 09:00 前通过苏采云完成投标文件递交，逾期系统将自动拒收。',
      '保留递交回执、文件哈希与操作日志，作为电子档案不可篡改存证。',
    ],
  },
}

function diurnal() {
  return Array.from({ length: 24 }, (_, h) => {
    const day = h >= 6 && h <= 18
    const rad = ((h - 6) / 12) * Math.PI
    return {
      h: `${String(h).padStart(2, '0')}:00`,
      nee: Math.round((day ? -Math.sin(rad) * 5.4 - 0.4 : 1.6) * 100) / 100,
      H: Math.round((day ? Math.sin(rad) * 140 : -18) * 10) / 10,
      LE: Math.round((day ? Math.sin(rad) * 190 : 10) * 10) / 10,
      ch4: 18 + (h > 20 || h < 6 ? 8 : 2),
      ebr: day ? 0.91 : 0.8,
    }
  })
}

export const FALLBACK_DASHBOARD = {
  kpis: {
    stationOnline: 3,
    stationTotal: 4,
    onlineRate: 75,
    heating: 1,
    meanNEE: -3.12,
    meanCH4: 32.4,
    meanEBR: 0.84,
    computeQueue: 1,
    batteryWarn: 1,
    qcGoodPct: 64.3,
  },
  diurnal: diurnal(),
  seasonal: [
    { season: 'DJF', nee: 18.4, gpp: 6.2, re: 24.6 },
    { season: 'MAM', nee: -42.8, gpp: 86.4, re: 43.6 },
    { season: 'JJA', nee: -128.6, gpp: 214.2, re: 85.6 },
    { season: 'SON', nee: -36.2, gpp: 72.8, re: 36.6 },
  ],
  mapPoints: [
    { name: 'QTP-FLUX-01', value: [91.9, 31.4, 80], status: 'ONLINE' },
    { name: 'QTP-FLUX-02', value: [102.8, 33.6, 90], status: 'ONLINE' },
    { name: 'QTP-FLUX-03', value: [92.9, 34.8, 70], status: 'WARNING_HEATING' },
    { name: 'QTP-FLUX-04', value: [99.5, 38.4, 95], status: 'ONLINE' },
  ],
  radar: [
    { name: 'CH4 湿地排放', value: 86 },
    { name: '草甸碳汇', value: 72 },
    { name: '冻土热通量', value: 58 },
    { name: '夜间 u*', value: 64 },
    { name: '能量闭合', value: 84 },
    { name: 'QC 优级占比', value: 64 },
  ],
  alerts: [
    { id: 'a1', time: '06:18', text: '风火山站光学透过率 74.5%，自动除霜已启动', level: 'danger' },
    { id: 'a2', time: '07:02', text: 'CSAT3B 声程积雪遮挡，加热中', level: 'warn' },
    { id: 'a3', time: '12:00', text: '那曲站半小时 NEE = −4.85 μmol m⁻² s⁻¹，WPL 已应用', level: 'ok' },
  ],
  configs: FALLBACK.configs,
  stations: FALLBACK.stations,
}
